// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AgenceImmoDbContext))]
    [Migration("20250802182549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BienAmenagement", b =>
                {
                    b.Property<int>("BienImmobilierId")
                        .HasColumnType("int");

                    b.Property<int>("AmenagementId")
                        .HasColumnType("int");

                    b.HasKey("BienImmobilierId", "AmenagementId")
                        .HasName("PK__BienAmen__DA6A2CF84E5EE8C9");

                    b.HasIndex("AmenagementId");

                    b.ToTable("BienAmenagements", (string)null);
                });

            modelBuilder.Entity("backend.Data.Amenagement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Amenagem__3214EC071346912E");

                    b.ToTable("Amenagements");
                });

            modelBuilder.Entity("backend.Data.BiensImmobilier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DateDePublication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<int>("NombreDeChambres")
                        .HasColumnType("int");

                    b.Property<int>("NombreDeCuisines")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("NombreDeSallesDeBain")
                        .HasColumnType("int");

                    b.Property<int>("NombreDeSalons")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("PrixParNuit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("StatutTransaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Surface")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TypeDeBienId")
                        .HasColumnType("int");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__BiensImm__3214EC07F5469088");

                    b.HasIndex("TypeDeBienId");

                    b.ToTable("BiensImmobiliers");
                });

            modelBuilder.Entity("backend.Data.Disponibilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienImmobilierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("PrixNuit")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Disponibilites__3214EC07");

                    b.HasIndex("BienImmobilierId");

                    b.ToTable("Disponibilites");
                });

            modelBuilder.Entity("backend.Data.ImagesBien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienImmobilierId")
                        .HasColumnType("int");

                    b.Property<bool>("EstImagePrincipale")
                        .HasColumnType("bit");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__ImagesBi__3214EC076D865796");

                    b.HasIndex("BienImmobilierId");

                    b.ToTable("ImagesBien", (string)null);
                });

            modelBuilder.Entity("backend.Data.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFacture")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateDePaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MethodeDePaiement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("StatutPaiement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Paiements__3214EC07");

                    b.HasIndex("ReservationId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("backend.Data.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienImmobilierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDeReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("NombreDeVoyageurs")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Reservations__3214EC07");

                    b.HasIndex("BienImmobilierId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("backend.Data.TypesDeBien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TypesDeB__3214EC07CA4D2CB8");

                    b.ToTable("TypesDeBien", (string)null);
                });

            modelBuilder.Entity("backend.Data.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MotDePasseHashe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomComplet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Utilisat__3214EC071A1239F9");

                    b.HasIndex(new[] { "NomUtilisateur" }, "UQ__Utilisat__49EDB0E510EF6AD5")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("BienAmenagement", b =>
                {
                    b.HasOne("backend.Data.Amenagement", null)
                        .WithMany()
                        .HasForeignKey("AmenagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BienAmenagements_Amenagements");

                    b.HasOne("backend.Data.BiensImmobilier", null)
                        .WithMany()
                        .HasForeignKey("BienImmobilierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BienAmenagements_BiensImmobiliers");
                });

            modelBuilder.Entity("backend.Data.BiensImmobilier", b =>
                {
                    b.HasOne("backend.Data.TypesDeBien", "TypeDeBien")
                        .WithMany("BiensImmobiliers")
                        .HasForeignKey("TypeDeBienId")
                        .IsRequired()
                        .HasConstraintName("FK_BiensImmobiliers_TypesDeBien");

                    b.Navigation("TypeDeBien");
                });

            modelBuilder.Entity("backend.Data.Disponibilite", b =>
                {
                    b.HasOne("backend.Data.BiensImmobilier", "BienImmobilier")
                        .WithMany("Disponibilites")
                        .HasForeignKey("BienImmobilierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Disponibilites_BiensImmobiliers");

                    b.Navigation("BienImmobilier");
                });

            modelBuilder.Entity("backend.Data.ImagesBien", b =>
                {
                    b.HasOne("backend.Data.BiensImmobilier", "BienImmobilier")
                        .WithMany("ImagesBiens")
                        .HasForeignKey("BienImmobilierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ImagesBien_BiensImmobiliers");

                    b.Navigation("BienImmobilier");
                });

            modelBuilder.Entity("backend.Data.Paiement", b =>
                {
                    b.HasOne("backend.Data.Reservation", "Reservation")
                        .WithMany("Paiements")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Paiements_Reservations");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("backend.Data.Reservation", b =>
                {
                    b.HasOne("backend.Data.BiensImmobilier", "BienImmobilier")
                        .WithMany("Reservations")
                        .HasForeignKey("BienImmobilierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_BiensImmobiliers");

                    b.HasOne("backend.Data.Utilisateur", "Utilisateur")
                        .WithMany("Reservations")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Utilisateurs");

                    b.Navigation("BienImmobilier");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("backend.Data.BiensImmobilier", b =>
                {
                    b.Navigation("Disponibilites");

                    b.Navigation("ImagesBiens");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("backend.Data.Reservation", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("backend.Data.TypesDeBien", b =>
                {
                    b.Navigation("BiensImmobiliers");
                });

            modelBuilder.Entity("backend.Data.Utilisateur", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
